
version: '3'
services:
  python: 
    #image: python:3.7
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./camino_form:/camino_form  
    ports: 
      - 8000:8000