# Generated by Django 2.2 on 2019-04-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissionData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelname',
            name='amount',
            field=models.IntegerField(help_text='Please Enter Loan Amount Required'),
        ),
    ]
