# Generated by Django 2.2 on 2019-04-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissionData', '0002_auto_20190420_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModelName',
            new_name='Loan',
        ),
    ]
